### ISSUE TITLE
pimatic not starting: error there is no hue station at the given adress

### ISSUE THREAD

**Issue by djmvt** [ch-world/pimatic-hue#7]
restarted the pi today because of a plug-in update but pimatic won't start.
error: There is no hue station at the given adress.
removing the hue plug-in from config.json is the only way to get pimatic starting again.

the curl rules I use to call scènes are still working so the hue bridge is reachable.

**Comment by ch-world** [comment]
Does this happen if you start pimatic by hand or if pimatic is starting during systemboot?

**Comment by djmvt** [comment]
both. cannot see the error when doing a systemboot because the system exits before errors are showing in the GUI. when starting with sudo pimatic.js this error is shown and pimatic stops.

**Comment by djmvt** [comment]
ok seems I was running the npm release, not the development release from git. learning every day ;)
installed directly from github seems to fix the problems. also errors are a lot "nicer" now.
