### ISSUE TITLE
IP address and username undefined

### ISSUE THREAD

**Issue by mkremeyer** [ch-world/pimatic-hue#8]
Plugin can't be initialized. Both host and key are undefined in connect(). Added their values to the error message to double check. Could potentially be a problem with naming the different variables in config.json and the CS/JS files, but I'm not familiar enough with the pimatic conventions. Let me know how I can help debugging/replicating the issue.

**Comment by djmvt** [comment]
There is a difference in naming between the npm package and the version here on github.
The github version requires host (ip) and username, the npm package also requires an id to connect. 
Plugin working ok here.

**Comment by mkremeyer** [comment]
Thanks for the quick response. Took some time but didn't find a solution. I have the npm version (0.0.4). It asks for host and apiKey. What id are you referring to? Is this documented somewhere? The first time I come across an ID is when I look at the individual bulbs (which makes sense). Not when I have to initialize the plugin.

Thanks for your help!

**Comment by djmvt** [comment]
Check in the config of your bridge: there is the user name you gave when creating the new user. But it's better to load the development version. Name and id variables are named right in the development version.

I am also just a user of the hue plugin ;)

**Comment by djmvt** [comment]
Here you can find your answer:

https://github.com/ch-world/pimatic-hue/issues/1

**Comment by mkremeyer** [comment]
Awesome, thanks for you help. Getting the plugin from github works. Not I gotta figure out how to add the devices. For some reason I don't get any debugging logs on hue.
